((org-mode . ((fill-column . 72)
              (line-spacing . 2)
              (org-hide-emphasis-markers . t)
              (sentence-end-double-space . t)
              (truncate-lines . nil)
              (eval . (org-superstar-mode +1))
              (eval . (visual-line-mode +1))
              (eval . (visual-fill-column-mode +1))
              (eval . (variable-pitch-mode +1)))))
